apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 9000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
    run: my-nginx
