apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
 tolerations:
- key: "node.kubernetes.io/unreachable"
  operator: "Exists"
  effect: "NoExecute"
  tolerationSeconds: 6000
  tolerations:
#  -key: special-user
#   operator: In
#   value: special-user
#   effect: NoSchedule
 containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
